USE [master]

GO

IF EXISTS(SELECT * FROM sys.databases WHERE [name] = 'MxgPetidDb')
BEGIN
	
	ALTER DATABASE MxgPetidDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

	DROP DATABASE MxgPetidDb

END

GO

IF NOT EXISTS(SELECT * FROM sys.databases WHERE [name] = 'MxgPetidDb')
BEGIN

	CREATE DATABASE MxgPetidDb

END

GO

IF EXISTS(SELECT * FROM sys.databases WHERE [name] = 'MxgPetidDb')
BEGIN

	USE MxgPetidDb

END

GO

IF EXISTS(SELECT * FROM sys.databases WHERE [name] = 'MxgPetidDb')
BEGIN

	CREATE TABLE [SESSION] (
	  SESSION_ID               uniqueidentifier NOT NULL, 
	  ACCESS_TOKEN             nvarchar(1500) NULL, 
	  REFRESH_TOKEN            nvarchar(max) NULL, 
	  REFRESH_TOKEN_EXPIRE     datetime NOT NULL, 
	  REFRESH_TOKEN_IS_USED    bit NOT NULL, 
	  REFRESH_TOKEN_IS_REVOKED bit NOT NULL, 
	  IP_ADDRESS               nvarchar(100) NULL, 
	  GEOGRAPHY                nvarchar(max) NULL, 
	  LATITUDE                 decimal(9, 6) NULL, 
	  LONGITUDE                decimal(9, 6) NULL, 
	  ALTITUDE                 float(10) NULL, 
	  USER_ID                  uniqueidentifier NOT NULL, 
	  IN_USE                   bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE                bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE             datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY               nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE       datetime NULL, 
	  LAST_MODIFIED_BY         nvarchar(255) NULL, 
	  MODIFIED_COUNT           int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (SESSION_ID));
	CREATE TABLE [USER] (
	  USER_ID                     uniqueidentifier NOT NULL, 
	  USERNAME                    nvarchar(32) NOT NULL, 
	  EMAIL                       nvarchar(100) NULL, 
	  EMAIL_CONFIRMED             bit DEFAULT '0' NOT NULL, 
	  EMAIL_CONFIRMED_CODE        nvarchar(10) NULL, 
	  PHONE_NUMBER                nvarchar(13) NULL, 
	  PHONE_NUMBER_CONFIRMED      bit DEFAULT '0' NOT NULL, 
	  PHONE_NUMBER_CONFIRMED_CODE nvarchar(10) NULL, 
	  BIRTHDATE                   date NULL, 
	  PASSWORD_HASH               nvarchar(max) NOT NULL, 
	  PRIVATE_INFO_JSON           nvarchar(max) NULL, 
	  IS_INFO_ENCRYPTED           bit DEFAULT '1' NOT NULL, 
	  GENDER_TYPE_ID              uniqueidentifier NULL, 
	  ALGORITHM_PASSWORD_TYPE_ID  uniqueidentifier NOT NULL, 
	  CITY_ID                     uniqueidentifier NULL, 
	  EMPLOYEED_COMPANY_ID        uniqueidentifier NULL, 
	  STATUS_ACCOUNT_TYPE_ID      uniqueidentifier NOT NULL, 
	  ROLE_ID                     uniqueidentifier NOT NULL, 
	  IN_USE                      bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE                   bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE                datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY                  nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE          datetime NULL, 
	  LAST_MODIFIED_BY            nvarchar(255) NULL, 
	  MODIFIED_COUNT              int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (USER_ID));
	CREATE TABLE COLLECTION_TYPE (
	  COLLECTION_TYPE_ID uniqueidentifier NOT NULL, 
	  CODE               nvarchar(15) NOT NULL, 
	  DESCRIPTION        varchar(255) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (COLLECTION_TYPE_ID));
	CREATE TABLE TYPE (
	  TYPE_ID            uniqueidentifier NOT NULL, 
	  CODE               nvarchar(15) NOT NULL, 
	  DESCRIPTION        nvarchar(255) NOT NULL, 
	  COLLECTION_TYPE_ID uniqueidentifier NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (TYPE_ID));
	CREATE TABLE PERMISSION (
	  PERMISSION_ID      uniqueidentifier NOT NULL, 
	  CODE               nvarchar(15) NOT NULL, 
	  DESCRIPTION        nvarchar(255) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (PERMISSION_ID));
	CREATE TABLE ROLE (
	  ROLE_ID            uniqueidentifier NOT NULL, 
	  CODE               nvarchar(15) NOT NULL, 
	  DESCRIPTION        nvarchar(255) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (ROLE_ID));
	CREATE TABLE ROLE_PERMISSION (
	  ROLE_ID            uniqueidentifier NOT NULL, 
	  PERMISSION_ID      uniqueidentifier NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (ROLE_ID, 
	  PERMISSION_ID));
	CREATE TABLE SETTING_USER (
	  SETTING_USER_ID    uniqueidentifier NOT NULL, 
	  CODE               varchar(15) NOT NULL, 
	  PREFERENCE         nvarchar(255) NOT NULL, 
	  GLOBAL_VALUE       nvarchar(max) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (SETTING_USER_ID));
	CREATE TABLE USER_SETTING_USER (
	  USER_ID            uniqueidentifier NOT NULL, 
	  SETTING_USER_ID    uniqueidentifier NOT NULL, 
	  CUSTOM_VALUE       nvarchar(max) NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (USER_ID, 
	  SETTING_USER_ID));
	CREATE TABLE PET (
	  PET_ID              uniqueidentifier NOT NULL, 
	  NAME                nvarchar(100) NULL, 
	  BIRTHDATE           date NULL, 
	  BREED               nvarchar(50) NULL, 
	  COLOR               nvarchar(30) NULL, 
	  WEIGHT              decimal(5, 2) NULL, 
	  DISTINCTIVE_FEATURE nvarchar(150) NULL, 
	  NOTES               nvarchar(500) NULL, 
	  PUBLIC_OWNER        nvarchar(150) NULL, 
	  PUBLIC_PHONE_NUMBER nvarchar(15) NULL, 
	  PUBLIC_EMAIL        nvarchar(150) NULL, 
	  PUBLIC_ADDRESS      nvarchar(max) NULL, 
	  GENDER_TYPE_ID      uniqueidentifier NULL, 
	  SPECIE_TYPE_ID      uniqueidentifier NULL, 
	  IDENTIFIER_TAG_ID   uniqueidentifier NOT NULL, 
	  CITY_ID             uniqueidentifier NULL, 
	  IN_USE              bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE           bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE        datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY          nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE  datetime NULL, 
	  LAST_MODIFIED_BY    nvarchar(255) NULL, 
	  MODIFIED_COUNT      int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (PET_ID));
	CREATE TABLE VACCINE (
	  VACCINE_ID            uniqueidentifier NOT NULL, 
	  NAME                  nvarchar(150) NOT NULL, 
	  DETAIL                nvarchar(max) NULL, 
	  VACCINE_APPLIED       date NOT NULL, 
	  NEXT_VACCINE          date NULL, 
	  PET_ID                uniqueidentifier NOT NULL, 
	  APPLIED_BY_COMPANY_ID uniqueidentifier NULL, 
	  IN_USE                bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE             bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE          datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY            nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE    datetime NULL, 
	  LAST_MODIFIED_BY      nvarchar(255) NULL, 
	  MODIFIED_COUNT        int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (VACCINE_ID));
	CREATE TABLE IDENTIFIER_TAG (
	  IDENTIFIER_TAG_ID      uniqueidentifier NOT NULL, 
	  PUBLIC_INDENTIFIER_TAG nvarchar(50) NOT NULL, 
	  SALE_PRICE             decimal(8, 2) NULL, 
	  PURCHASE_COST          decimal(8, 2) NULL, 
	  TAG_TYPE_ID            uniqueidentifier NOT NULL, 
	  IN_USE                 bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE              bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE           datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY             nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE     datetime NULL, 
	  LAST_MODIFIED_BY       nvarchar(255) NULL, 
	  MODIFIED_COUNT         int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (IDENTIFIER_TAG_ID));
	CREATE TABLE CITY (
	  CITY_ID            uniqueidentifier NOT NULL, 
	  CODE               nvarchar(15) NOT NULL, 
	  NAME               nvarchar(255) NOT NULL, 
	  STATE_ID           uniqueidentifier NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (CITY_ID));
	CREATE TABLE STATE (
	  STATE_ID           uniqueidentifier NOT NULL, 
	  CODE               varchar(15) NOT NULL, 
	  NAME               nvarchar(255) NOT NULL, 
	  COUNTRY_ID         uniqueidentifier NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (STATE_ID));
	CREATE TABLE COUNTRY (
	  COUNTRY_ID         uniqueidentifier NOT NULL, 
	  CODE               varchar(15) NOT NULL, 
	  NAME               nvarchar(255) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (COUNTRY_ID));
	CREATE TABLE COMPANY (
	  COMPANY_ID         uniqueidentifier NOT NULL, 
	  NAME               nvarchar(100) NOT NULL, 
	  ADDRESS            nvarchar(255) NULL, 
	  OWNER_USER_ID      uniqueidentifier NULL, 
	  CITY_ID            uniqueidentifier NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (COMPANY_ID));
	CREATE TABLE RESOURCE (
	  RESOURCE_ID            uniqueidentifier NOT NULL, 
	  URI                    nvarchar(500) NOT NULL, 
	  FILE_NAME              nvarchar(50) NOT NULL, 
	  ORDER_PICTURE          tinyint NULL, 
	  EXTENSION_FILE_TYPE_ID uniqueidentifier NOT NULL, 
	  STORAGE_TYPE_ID        uniqueidentifier NOT NULL, 
	  PET_ID                 uniqueidentifier NULL, 
	  VACCINE_ID             uniqueidentifier NULL, 
	  PRODUCT_ID             uniqueidentifier NULL, 
	  IN_USE                 bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE              bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE           datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY             nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE     datetime NULL, 
	  LAST_MODIFIED_BY       nvarchar(255) NULL, 
	  MODIFIED_COUNT         int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (RESOURCE_ID));
	CREATE TABLE PRODUCT (
	  PRODUCT_ID         uniqueidentifier NOT NULL, 
	  CODE               varchar(15) NOT NULL, 
	  NAME               nvarchar(100) NOT NULL, 
	  DESCRIPTION        varchar(255) NOT NULL, 
	  SALE_PRICE         decimal(8, 2) NOT NULL, 
	  PURCHASE_PRICE     decimal(8, 2) NOT NULL, 
	  IN_USE             bit DEFAULT '0' NOT NULL, 
	  IS_ACTIVE          bit DEFAULT '1' NOT NULL, 
	  CREATED_DATE       datetime DEFAULT SYSUTCDATETIME() NOT NULL, 
	  CREATED_BY         nvarchar(255) NOT NULL, 
	  LAST_MODIFIED_DATE datetime NULL, 
	  LAST_MODIFIED_BY   nvarchar(255) NULL, 
	  MODIFIED_COUNT     int DEFAULT 0 NOT NULL, 
	  PRIMARY KEY (PRODUCT_ID));
	CREATE UNIQUE INDEX USER_USERNAME 
	  ON [USER] (USERNAME);
	CREATE INDEX USER_EMAIL 
	  ON [USER] (EMAIL);
	CREATE INDEX USER_PHONE_NUMBER 
	  ON [USER] (PHONE_NUMBER);
	CREATE UNIQUE INDEX COLLECTION_TYPE_CODE 
	  ON COLLECTION_TYPE (CODE);
	CREATE UNIQUE INDEX TYPE_CODE 
	  ON TYPE (CODE);
	CREATE UNIQUE INDEX PERMISSION_CODE 
	  ON PERMISSION (CODE);
	CREATE UNIQUE INDEX ROLE_CODE 
	  ON ROLE (CODE);
	CREATE UNIQUE INDEX IDENTIFIER_TAG_PUBLIC_INDENTIFIER_TAG 
	  ON IDENTIFIER_TAG (PUBLIC_INDENTIFIER_TAG);
	CREATE INDEX PRODUCT_CODE 
	  ON PRODUCT (CODE);
	ALTER TABLE [SESSION] ADD CONSTRAINT FKSESSION621984 FOREIGN KEY (USER_ID) REFERENCES [USER] (USER_ID);
	ALTER TABLE TYPE ADD CONSTRAINT FKTYPE732746 FOREIGN KEY (COLLECTION_TYPE_ID) REFERENCES COLLECTION_TYPE (COLLECTION_TYPE_ID);
	ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT FKROLE_PERMI113911 FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);
	ALTER TABLE ROLE_PERMISSION ADD CONSTRAINT FKROLE_PERMI854622 FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (PERMISSION_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER501579 FOREIGN KEY (ALGORITHM_PASSWORD_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE USER_SETTING_USER ADD CONSTRAINT FKUSER_SETTI86753 FOREIGN KEY (USER_ID) REFERENCES [USER] (USER_ID);
	ALTER TABLE USER_SETTING_USER ADD CONSTRAINT FKUSER_SETTI654990 FOREIGN KEY (SETTING_USER_ID) REFERENCES SETTING_USER (SETTING_USER_ID);
	ALTER TABLE VACCINE ADD CONSTRAINT FKVACCINE159961 FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID);
	ALTER TABLE PET ADD CONSTRAINT FKPET530059 FOREIGN KEY (IDENTIFIER_TAG_ID) REFERENCES IDENTIFIER_TAG (IDENTIFIER_TAG_ID);
	ALTER TABLE STATE ADD CONSTRAINT FKSTATE376609 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID);
	ALTER TABLE CITY ADD CONSTRAINT FKCITY969245 FOREIGN KEY (STATE_ID) REFERENCES STATE (STATE_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER378927 FOREIGN KEY (CITY_ID) REFERENCES CITY (CITY_ID);
	ALTER TABLE IDENTIFIER_TAG ADD CONSTRAINT FKIDENTIFIER319790 FOREIGN KEY (TAG_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER619308 FOREIGN KEY (GENDER_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER499795 FOREIGN KEY (STATUS_ACCOUNT_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER36891 FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID);
	ALTER TABLE PET ADD CONSTRAINT FKPET914045 FOREIGN KEY (CITY_ID) REFERENCES CITY (CITY_ID);
	ALTER TABLE [USER] ADD CONSTRAINT FKUSER857085 FOREIGN KEY (EMPLOYEED_COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
	ALTER TABLE VACCINE ADD CONSTRAINT FKVACCINE348294 FOREIGN KEY (APPLIED_BY_COMPANY_ID) REFERENCES COMPANY (COMPANY_ID);
	ALTER TABLE PET ADD CONSTRAINT FKPET130838 FOREIGN KEY (SPECIE_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE PET ADD CONSTRAINT FKPET154427 FOREIGN KEY (GENDER_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE COMPANY ADD CONSTRAINT FKCOMPANY475300 FOREIGN KEY (CITY_ID) REFERENCES CITY (CITY_ID);
	ALTER TABLE RESOURCE ADD CONSTRAINT FKRESOURCE985080 FOREIGN KEY (STORAGE_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE RESOURCE ADD CONSTRAINT FKRESOURCE976990 FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID);
	ALTER TABLE COMPANY ADD CONSTRAINT FKCOMPANY167657 FOREIGN KEY (OWNER_USER_ID) REFERENCES [USER] (USER_ID);
	ALTER TABLE RESOURCE ADD CONSTRAINT FKRESOURCE108458 FOREIGN KEY (VACCINE_ID) REFERENCES VACCINE (VACCINE_ID);
	ALTER TABLE RESOURCE ADD CONSTRAINT FKRESOURCE946400 FOREIGN KEY (EXTENSION_FILE_TYPE_ID) REFERENCES TYPE (TYPE_ID);
	ALTER TABLE RESOURCE ADD CONSTRAINT FKRESOURCE368186 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

	--/////////////////////////////////////////////////////////////////////////////////////////

	USE MxgPetidDb

	IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'user.temp')
	BEGIN
		CREATE USER [user.temp] FOR LOGIN [user.temp];
		ALTER ROLE [db_owner] ADD MEMBER [user.temp];
	END

END
