USE MxgPetidDb

GO

BEGIN TRY
BEGIN TRANSACTION

	IF EXISTS(SELECT 1 FROM [master].sys.databases WITH(NOLOCK) WHERE [name] = 'MxgPetidDb') AND
	   NOT EXISTS(SELECT 1 FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = 'ALGTCRYP') 
	BEGIN

		--====================================================== COLLECTION TYPES

		DECLARE @collectionType_AlgorithmEncrypt AS NVARCHAR(10) = 'ALGTCRYP'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_AlgorithmEncrypt, 
			'Algorithm to encrypt collection.',
			1,
			SYSUTCDATETIME(),
			'-3')

		--

		DECLARE @collectionType_GenderPerson AS NVARCHAR(10) = 'GNDPRS'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_GenderPerson, 
			'Gender Person collection.',
			1,
			SYSUTCDATETIME(),
			'-3')

		--

		DECLARE @collectionType_GenderPet AS NVARCHAR(10) = 'GNDPET'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_GenderPet, 
			'Gender Pet collection.',
			1,
			SYSUTCDATETIME(),
			'-3')

		--

		DECLARE @collectionType_StatusAccount AS NVARCHAR(10) = 'STSACC'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_StatusAccount, 
			'Status Account collection.',
			1,
			SYSUTCDATETIME(),
			'-3')

		--

		DECLARE @collectionType_IdentifierTag AS NVARCHAR(10) = 'IDETAG'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_IdentifierTag, 
			'Identifier Tag collection.',
			'-3')

		--

		DECLARE @collectionType_ResourceStorage AS NVARCHAR(10) = 'RESSTOR'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_ResourceStorage, 
			'Resource Storage collection.',
			'-3')

		--

		DECLARE @collectionType_Extension AS NVARCHAR(10) = 'EXTNCOL'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_Extension, 
			'Extension collection.',
			'-3')

		--

		DECLARE @collectionType_SpeciesAnimal AS NVARCHAR(10) = 'SPECANIM'

		INSERT INTO COLLECTION_TYPE(
			COLLECTION_TYPE_ID, CODE, [DESCRIPTION], CREATED_BY) 
		VALUES(
			NEWID(),
			@collectionType_SpeciesAnimal, 
			'Specie of animal collection.',
			'-3')

		--====================================================== TYPE

		-- ALGTCRYP - Algorithm to encrypt.

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'SHA256', 'Algorithm SHA-256.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_AlgorithmEncrypt),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'SHA256IDNT', 'Algorithm SHA-256 from Entity Framework Identity.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_AlgorithmEncrypt),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'BCRYPT', 'Algorithm Bcrypt.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_AlgorithmEncrypt),
			SYSUTCDATETIME(), '-3')

		-- GNDPRS - Gender Person.

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MALGND', 'Male gender.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_GenderPerson),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'FEMGND', 'Female gender.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_GenderPerson),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'PLUGND', 'LGBTQIA+ gender.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_GenderPerson),
			SYSUTCDATETIME(), '-3')

		-- GNDPET - Gender Pet.

		DECLARE @type_Code_GenderMalePet_Id AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			@type_Code_GenderMalePet_Id, 'PMALGND', 'Male pet gender.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_GenderPet),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'PFEMGND', 'Female pet gender.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_GenderPet),
			SYSUTCDATETIME(), '-3')

		-- STSACC - Status Account.

		DECLARE @collectionType_StatusAccount_Active AS NVARCHAR(10) = 'STSAACT'

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), @collectionType_StatusAccount_Active, 'Status account active.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_StatusAccount),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'STSADEACOW', 'Status account deactivate by owner.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_StatusAccount),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'STSARES', 'Status account restricted.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_StatusAccount),
			SYSUTCDATETIME(), '-3')

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'STSABLC', 'Status account blocked.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_StatusAccount),
			SYSUTCDATETIME(), '-3')

		--

		DECLARE @typeCode_Basic1024 AS NVARCHAR(10) = 'BSC1024'

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), @typeCode_Basic1024, 'Basic identifier tag model 1024.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_IdentifierTag),
			SYSUTCDATETIME(), '-3')

		--

		DECLARE @typeCode_StorageType_LocalDirectory AS NVARCHAR(10) = 'LCSYSDCT'

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), @typeCode_StorageType_LocalDirectory, 'Local system directory.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_ResourceStorage),
			SYSUTCDATETIME(), '-3')

		DECLARE @typeCodeStorageTypeCloudDropboxId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			@typeCodeStorageTypeCloudDropboxId, 'CLDDRPBX', 'Cloud Dropbox repostirory.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_ResourceStorage),
			SYSUTCDATETIME(), '-3')

		--

		DECLARE @typeCodeExtensionTypeJpgId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			@typeCodeExtensionTypeJpgId, 'JPGTYP', 'Jpg extension file.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_Extension),
			SYSUTCDATETIME(), '-3')

		--

		DECLARE @type_SpecieAnimal_Canine_Id AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO [TYPE](
			[TYPE_ID], CODE, [DESCRIPTION], COLLECTION_TYPE_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			@type_SpecieAnimal_Canine_Id, 'CANITYP', 'Canine specie.',
			(SELECT TOP(1) COLLECTION_TYPE_ID FROM COLLECTION_TYPE WITH(NOLOCK) WHERE CODE = @collectionType_SpeciesAnimal),
			SYSUTCDATETIME(), '-3')

		--====================================================== ROLE

		INSERT INTO [ROLE](
			ROLE_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'CUSTUSR', 'Customer user.', 
			SYSUTCDATETIME(), '-3')

		DECLARE @roleCode_AdminUser AS NVARCHAR(10) = 'ADMIUSR'

		INSERT INTO [ROLE](
			ROLE_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), @roleCode_AdminUser, 'Admin user.', 
			SYSUTCDATETIME(), '-3')

		--====================================================== PERMISSION

		-- ROLE

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDROL', 'Read roles.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDROL', 'Add roles.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYROL', 'Modify roles.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELROL', 'Delete roles.', SYSUTCDATETIME(), '-3')

		-- PERMISSION

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDPRMS', 'Read permissions.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDPRMS', 'Add permissions.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYPRMS', 'Modify permissions.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELPRMS', 'Delete permissions.', SYSUTCDATETIME(), '-3')

		-- ACCOUNT

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'CHNGACCN', 'Change type accounts.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DEACACCN', 'Deactivate accounts.', SYSUTCDATETIME(), '-3')

		-- PET

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDPET', 'Read pets.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDPET', 'Add pets.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYPET', 'Modify pets.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELPET', 'Delete pets.', SYSUTCDATETIME(), '-3')

		-- COMPANY

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDCOMPY', 'Read companies.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDCOMPY', 'Add companies.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYCOMPY', 'Modify companies.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELCOMPY', 'Delete companies.', SYSUTCDATETIME(), '-3')

		-- TAG

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDIDTAG', 'Read tags.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDIDTAG', 'Add tags.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYIDTAG', 'Modify tags.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELIDTAG', 'Delete tags.', SYSUTCDATETIME(), '-3')

		-- VACCINES

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDVAC', 'Read vaccines.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDVAC', 'Add vaccines.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYVAC', 'Modify vaccines.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELVAC', 'Delete vaccines.', SYSUTCDATETIME(), '-3')

		-- PRODUCTS

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'REDPROD', 'Read Products.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'ADDPROD', 'Add Products.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'MDYPROD', 'Modify Products.', SYSUTCDATETIME(), '-3')

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(), 'DELPROD', 'Delete Products.', SYSUTCDATETIME(), '-3')

		-- F. = Front Application ... W. = W Application ... M = Mobile Application ... ONE = One ... MUL = Multi

		--INSERT INTO PERMISSION(
		--	PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		--VALUES(
		--	NEWID(), 'F.REDONEACCN', 'Read one account (Front Application).', SYSUTCDATETIME(), '-3')

		--INSERT INTO PERMISSION(
		--	PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		--VALUES(
		--	NEWID(), 'F.REDMULACCN', 'Read multi accounts (Front Application).', SYSUTCDATETIME(), '-3')

		DECLARE @permissionMyAccnId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			@permissionMyAccnId, 'F.MYACCN', 'My account route (Front Application).', SYSUTCDATETIME(), '-3')

		DECLARE @permissionManagId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO PERMISSION(
			PERMISSION_ID, CODE, [DESCRIPTION], CREATED_DATE, CREATED_BY) 
		VALUES(
			@permissionManagId, 'F.MANAG', 'Management route (Front Application).', SYSUTCDATETIME(), '-3')

		--====================================================== ROLE_PERMISSION (CUSTUSR)

		DECLARE @roleCode_CustomerUser AS NVARCHAR(10)

		SET @roleCode_CustomerUser = 'CUSTUSR'

		-- ROL

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDROL'),
			SYSUTCDATETIME(), '-3')

		-- PERMISSION

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDPRMS'),
			SYSUTCDATETIME(), '-3')

		-- ACCOUNT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DEACACCN'),
			SYSUTCDATETIME(), '-3')

		-- PET

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDPET'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDPET'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYPET'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELPET'),
			SYSUTCDATETIME(), '-3')

		-- VACCINE

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDVAC'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDVAC'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYVAC'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELVAC'),
			SYSUTCDATETIME(), '-3')

		-- PRODUCT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_CustomerUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDPROD'),
			SYSUTCDATETIME(), '-3')

		-- FRONT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_CustomerUser),
			@permissionMyAccnId,
			SYSUTCDATETIME(), '-3')

		--====================================================== ROLE_PERMISSION (ADMIUSR)

		-- ACCOUNT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'CHNGACCN'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DEACACCN'),
			SYSUTCDATETIME(), '-3')

		 -- TAG

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDIDTAG'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDIDTAG'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYIDTAG'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELIDTAG'),
			SYSUTCDATETIME(), '-3')

		-- COMPANY

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDCOMPY'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDCOMPY'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYCOMPY'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELCOMPY'),
			SYSUTCDATETIME(), '-3')

		-- ROL

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDROL'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDROL'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYROL'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELROL'),
			SYSUTCDATETIME(), '-3')

		-- PERMISSION

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDPRMS'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDPRMS'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYPRMS'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELPRMS'),
			SYSUTCDATETIME(), '-3')

		-- PRODUCT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'REDPROD'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'ADDPROD'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'MDYPROD'),
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			(SELECT TOP(1) PERMISSION_ID FROM [PERMISSION] WITH(NOLOCK) WHERE CODE = 'DELPROD'),
			SYSUTCDATETIME(), '-3')

		-- FRONT

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			@permissionMyAccnId,
			SYSUTCDATETIME(), '-3')

		INSERT INTO ROLE_PERMISSION(
			ROLE_ID, PERMISSION_ID, CREATED_DATE, CREATED_BY) 
		VALUES(
			(SELECT TOP(1) ROLE_ID FROM [ROLE] WITH(NOLOCK) WHERE CODE =  @roleCode_AdminUser),
			@permissionManagId,
			SYSUTCDATETIME(), '-3')

		--======================================================

		DECLARE @countryCodeMx AS NVARCHAR(10) = 'MX'

		INSERT INTO COUNTRY(
			COUNTRY_ID, CODE, [NAME], CREATED_BY) 
		VALUES(
			NEWID(),
			@countryCodeMx,
			'M XICO',
			'-3')

		--======================================================

		DECLARE @stateCodeCoahuila AS NVARCHAR(10) = 'COH'

		INSERT INTO [STATE](
			STATE_ID, CODE, [NAME], COUNTRY_ID, CREATED_BY) 
		VALUES(
			NEWID(),
			@stateCodeCoahuila,
			'COAHUILA',
			(SELECT TOP(1) COUNTRY_ID FROM COUNTRY WITH(NOLOCK) WHERE CODE = @countryCodeMx),
			'-3')

		--

		DECLARE @stateCodeDurango AS NVARCHAR(10) = 'DGO'

		INSERT INTO [STATE](
			STATE_ID, CODE, [NAME], COUNTRY_ID, CREATED_BY) 
		VALUES(
			NEWID(),
			@stateCodeDurango,
			'DURANGO',
			(SELECT TOP(1) COUNTRY_ID FROM COUNTRY WITH(NOLOCK) WHERE CODE = @countryCodeMx),
			'-3')

		--======================================================

		INSERT INTO [CITY](
			CITY_ID, CODE, [NAME], STATE_ID, CREATED_BY) 
		VALUES(
			NEWID(),
			'TRC',
			'TORREÓN',
			(SELECT TOP(1) STATE_ID FROM [STATE] WITH(NOLOCK) WHERE CODE = @stateCodeCoahuila),
			'-3')

		--

		INSERT INTO [CITY](
			CITY_ID, CODE, [NAME], STATE_ID, CREATED_BY) 
		VALUES(
			NEWID(),
			'GMZ',
			'GOMEZ PALACIO',
			(SELECT TOP(1) STATE_ID FROM [STATE] WITH(NOLOCK) WHERE CODE = @stateCodeDurango),
			'-3')

		--

		DECLARE @cityCodeLerdo AS NVARCHAR(10) = 'LRD'

		INSERT INTO [CITY](
			CITY_ID, CODE, [NAME], STATE_ID, CREATED_BY) 
		VALUES(
			NEWID(),
			@cityCodeLerdo,
			'LERDO',
			(SELECT TOP(1) STATE_ID FROM [STATE] WITH(NOLOCK) WHERE CODE = @stateCodeDurango),
			'-3')

		--======================================================

		INSERT INTO [USER](
			[USER_ID], USERNAME, EMAIL, PHONE_NUMBER, PHONE_NUMBER_CONFIRMED, [PASSWORD_HASH], PRIVATE_INFO_JSON, GENDER_TYPE_ID, ALGORITHM_PASSWORD_TYPE_ID, CITY_ID, STATUS_ACCOUNT_TYPE_ID, ROLE_ID, CREATED_DATE, CREATED_BY)
		VALUES(
			NEWID(),
			'52CA97585A464BD7BDF4A88158CF9EB3', -- USERNAME
			'admin@admin.com', -- EMAIL
			NULL, -- PHONE_NUMBER
			1, -- PHONE_NUMBER_CONFIRMED
			'$2a$11$IdFpWVh2ac4HuXnUOh.gcOpcbVA7NpGGZDc2ikIbc/tOK.65JCssO', -- [PASSWORD_HASH]
			'eEG04IAaEr3TPkptaGDIyto/0oN15aRMwfMC+szat/VAqsiSW6SHnLgKUE9rTCdJBiJ8uGLZy8UeSnabz8uBqFY/lfM6jeFc76n9LxVYlaIRJb8baCoRY7cT0cu2r9wYvKg/eSGQKyqBqFAmeXAkQmMJC74uFaUVdSUSteGiUdlhoWt9Q2q7xmUuLzfpYpzDl52G1eKwDv0Sb5dFALwARKmrV+Szpnb4fiWf2u8+epAWqVOKRkAyoqRkMPQllzEz',--'{"firstName": null, "lastName": null, "birthDate": null, "genderTypeId": null}', -- PRIVATE_INFO_JSON
			(SELECT TOP(1) [TYPE_ID] FROM [TYPE] WITH(NOLOCK) WHERE CODE = 'MALGND'), -- GENDER_TYPE_ID
			(SELECT TOP(1) [TYPE_ID] FROM [TYPE] WITH(NOLOCK) WHERE CODE = 'BCRYPT'), -- ALGORITHM_PASSWORD_TYPE_ID
			NULL, -- CITY_ID
			(SELECT TOP(1) [TYPE_ID] FROM [TYPE] WITH(NOLOCK) WHERE CODE = @collectionType_StatusAccount_Active), -- STATUS_ACCOUNT_TYPE_ID
			(SELECT TOP(1) [ROLE_ID] FROM [ROLE] WITH(NOLOCK) WHERE CODE = @roleCode_AdminUser), -- ROLE_ID
			SYSUTCDATETIME(), -- CREATED_DATE
			'-3' -- CREATED_BY
		)

		--======================================================

		DECLARE @publicIdentifierTag AS NVARCHAR(50) = '02D7D9C375124361AAF6A4BADE9AEBD5'

		INSERT INTO IDENTIFIER_TAG(
			IDENTIFIER_TAG_ID, PUBLIC_INDENTIFIER_TAG, TAG_TYPE_ID, CREATED_BY)
		VALUES(
			NEWID(),
			@publicIdentifierTag,
			(SELECT TOP(1) [TYPE_ID] FROM [TYPE] WITH(NOLOCK) WHERE CODE = @typeCode_Basic1024),
			'-3' -- CREATED_BY
		)
		
		DECLARE @publicIdentifierTag2 AS NVARCHAR(50) = 'E40D51519E344ED3AA98D6B30A312132'

		INSERT INTO IDENTIFIER_TAG(
			IDENTIFIER_TAG_ID, PUBLIC_INDENTIFIER_TAG, TAG_TYPE_ID, CREATED_BY)
		VALUES(
			NEWID(),
			@publicIdentifierTag2,
			(SELECT TOP(1) [TYPE_ID] FROM [TYPE] WITH(NOLOCK) WHERE CODE = @typeCode_Basic1024),
			'-3' -- CREATED_BY
		)

		--======================================================

		DECLARE @petId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO PET(
			PET_ID, [NAME], BIRTHDATE, BREED, COLOR, [WEIGHT], NOTES, PUBLIC_EMAIL, PUBLIC_ADDRESS, GENDER_TYPE_ID, SPECIE_TYPE_ID, IDENTIFIER_TAG_ID, CITY_ID, CREATED_BY)
		VALUES(
			@petId, -- PET_ID
			'Nito', -- [NAME]
			'2021-01-01', -- BIRTHDATE
			'Criolla', -- BREED
			'Negro, Blanco, Café', -- COLOR
			3.5, -- [WEIGHT]
			'El perrito ya tiene algunas vacunas, incluyendo la antirrabica.', -- NOTE
			'straadlin@gmail.com', -- PUBLIC_EMAIL
			'Cerrada San Fernando, Colonia Centro.', -- PUBLIC_ADDRESS
			@type_Code_GenderMalePet_Id, -- GENDER_TYPE_ID
			@type_SpecieAnimal_Canine_Id,
			(SELECT TOP(1) IDENTIFIER_TAG_ID FROM IDENTIFIER_TAG WITH(NOLOCK) WHERE PUBLIC_INDENTIFIER_TAG = @publicIdentifierTag), -- IDENTIFIER_TAG_ID
			(SELECT TOP(1) CITY_ID FROM CITY WITH(NOLOCK) WHERE CODE = @cityCodeLerdo), -- CITY_ID
			'-3' -- CREATED_BY
		)

		INSERT INTO PET(
			PET_ID, [NAME], COLOR, PUBLIC_EMAIL, PUBLIC_ADDRESS, NOTES, IDENTIFIER_TAG_ID, CITY_ID, CREATED_BY)
		VALUES(
			NEWID(),
			'Nito2',
			NULL,
			NULL,
			NULL,
			NULL, -- NOTE
			(SELECT TOP(1) IDENTIFIER_TAG_ID FROM IDENTIFIER_TAG WITH(NOLOCK) WHERE PUBLIC_INDENTIFIER_TAG = @publicIdentifierTag2), -- IDENTIFIER_TAG_ID
			NULL, -- CITY_ID
			'-3' -- CREATED_BY
		)

		--======================================================

		DECLARE @vaccineId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO VACCINE(
			VACCINE_ID, [NAME], DETAIL, VACCINE_APPLIED, NEXT_VACCINE, PET_ID, CREATED_BY)
		VALUES(
			@vaccineId,
			'Canomune',
			'Inmunización de perros de 6 semanas o mayores contra el Moquillo, Parvovirus, Adenovirus tipo 2, Hepatitis infecciosa canina y Parainfluenza canina.',
			'2024-07-26',
			'2025-08-09',
			@petId,
			'-3' -- CREATED_BY
		)

		INSERT INTO VACCINE(
			VACCINE_ID, [NAME], DETAIL, VACCINE_APPLIED, NEXT_VACCINE, PET_ID, CREATED_BY)
		VALUES(
			NEWID(),
			'Diluyente Estéril',
			'Agua esteril inyectable.',
			'2024-07-26',
			NULL,
			@petId,
			'-3' -- CREATED_BY
		)

		INSERT INTO VACCINE(
			VACCINE_ID, [NAME], DETAIL, VACCINE_APPLIED, NEXT_VACCINE, PET_ID, CREATED_BY)
		VALUES(
			NEWID(),
			'Bordetella',
			NULL,
			'2024-08-15',
			NULL,
			@petId,
			'-3' -- CREATED_BY
		)

		INSERT INTO VACCINE(
			VACCINE_ID, [NAME], DETAIL, VACCINE_APPLIED, NEXT_VACCINE, PET_ID, CREATED_BY)
		VALUES(
			NEWID(),
			'Rabimune',
			NULL,
			'2024-08-15',
			'2025-03-15',
			@petId,
			'-3' -- CREATED_BY
		)

		INSERT INTO VACCINE(
			VACCINE_ID, [NAME], DETAIL, VACCINE_APPLIED, NEXT_VACCINE, PET_ID, CREATED_BY)
		VALUES(
			NEWID(),
			'Pastilla Antigarrapatas',
			'Pastilla para eliminar garrapatas y pulgas.',
			'2024-12-08',
			NULL,
			@petId,
			'-3' -- CREATED_BY
		)

		--======================================================

		INSERT INTO RESOURCE(
			RESOURCE_ID, URI, [FILE_NAME], EXTENSION_FILE_TYPE_ID, STORAGE_TYPE_ID, PET_ID, VACCINE_ID, 
			CREATED_BY)
		VALUES(
			NEWID(), -- RESOURCE_ID
			'https://www.dropbox.com/scl/fi/3dnvn44pb2rcwz5zje0yg/cd9a415069d94b67856e9285967e71a3.jpg?rlkey=fsf86csopw0v39tmgip06j2ss&st=oh1wu1jf&raw=1', -- URI
			'0ceffdbc65454b2eab052fa96196fe80.jpg', -- FILE_NAME
			@typeCodeExtensionTypeJpgId, -- EXTENSION_FILE_TYPE_ID
			@typeCodeStorageTypeCloudDropboxId, -- STORAGE_TYPE_ID
			@petId, -- PET_ID
			NULL, -- VACCINE_ID
			'-3') -- CREATED_BY

		INSERT INTO RESOURCE(
			RESOURCE_ID, URI, [FILE_NAME], EXTENSION_FILE_TYPE_ID, STORAGE_TYPE_ID, PET_ID, VACCINE_ID, 
			CREATED_BY)
		VALUES(
			NEWID(), -- RESOURCE_ID
			'https://www.dropbox.com/scl/fi/tl1xonrw563887k8qajs9/0ceffdbc65454b2eab052fa96196fe80.jpg?rlkey=hprtoy3ovw21nwvhodgclo8pz&st=i8trki8z&raw=1', -- URI
			'cd9a415069d94b67856e9285967e71a3.jpg', -- FILE_NAME
			@typeCodeExtensionTypeJpgId, -- EXTENSION_FILE_TYPE_ID
			@typeCodeStorageTypeCloudDropboxId, -- STORAGE_TYPE_ID
			@petId, -- PET_ID
			NULL, -- VACCINE_ID
			'-3') -- CREATED_BY

		INSERT INTO RESOURCE(
			RESOURCE_ID, URI, [FILE_NAME], EXTENSION_FILE_TYPE_ID, STORAGE_TYPE_ID, PET_ID, VACCINE_ID, 
			CREATED_BY)
		VALUES(
			NEWID(), -- RESOURCE_ID
			'https://www.dropbox.com/scl/fi/3bc6m1z3kvi6vd5jet0jo/4d512d0f925246049377f15a71237856.jpg?rlkey=2fgsrm4cym2sgoyahlfc8f2pg&st=10r1ewi1&raw=1', -- URI
			'4d512d0f925246049377f15a71237856.jpg', -- FILE_NAME
			@typeCodeExtensionTypeJpgId, -- EXTENSION_FILE_TYPE_ID
			@typeCodeStorageTypeCloudDropboxId, -- STORAGE_TYPE_ID
			NULL, -- PET_ID
			@vaccineId, -- VACCINE_ID
			'-3') -- CREATED_BY

		INSERT INTO RESOURCE(
			RESOURCE_ID, URI, [FILE_NAME], EXTENSION_FILE_TYPE_ID, STORAGE_TYPE_ID, PET_ID, VACCINE_ID, 
			CREATED_BY)
		VALUES(
			NEWID(), -- RESOURCE_ID
			'https://www.dropbox.com/scl/fi/uz9fhuk1iao1bi01k9gdo/bf8c3baace394e249f25f20025040a3a.jpg?rlkey=escj904ouu4sys6huqldxntk1&st=es7p1tf1&raw=1', -- URI
			'bf8c3baace394e249f25f20025040a3a.jpg', -- FILE_NAME
			@typeCodeExtensionTypeJpgId, -- EXTENSION_FILE_TYPE_ID
			@typeCodeStorageTypeCloudDropboxId, -- STORAGE_TYPE_ID
			NULL, -- PET_ID
			@vaccineId, -- VACCINE_ID
			'-3') -- CREATED_BY

		--======================================================

		DECLARE @productId AS UNIQUEIDENTIFIER = NEWID()

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			@productId,--PRODUCT_ID
			'ABCDEFGHIJ1',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ2',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ3',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ4',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ5',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ6',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		INSERT INTO PRODUCT(
			PRODUCT_ID, CODE, [NAME], [DESCRIPTION], SALE_PRICE, PURCHASE_PRICE, 
			IN_USE, IS_ACTIVE, CREATED_DATE, CREATED_BY) 
		VALUES(
			NEWID(),--PRODUCT_ID
			'ABCDEFGHIJ7',--CODE
			'NAME',--[NAME]
			'DESCRIPTION',--[DESCRIPTION]
			10.00,--SALE_PRICE
			11.00,--PURCHASE_PRICE
			1,--IN_USE
			1,--IS_ACTIVE
			SYSUTCDATETIME(),--CREATED_DATE
			'-3')--CREATED_BY

		--

		INSERT INTO [RESOURCE](
			RESOURCE_ID, URI, [FILE_NAME], ORDER_PICTURE, EXTENSION_FILE_TYPE_ID, STORAGE_TYPE_ID, PET_ID, VACCINE_ID, PRODUCT_ID, CREATED_BY) 
		VALUES(
			NEWID(),--RESOURCE_ID
			'https://www.dropbox.com/scl/fi/uz9fhuk1iao1bi01k9gdo/bf8c3baace394e249f25f20025040a3a.jpg?rlkey=escj904ouu4sys6huqldxntk1&st=es7p1tf1&raw=1',--URI
			'bf8c3baace394e249f25f20025040a3a',--[FILE_NAME]
			1,--ORDER_PICTURE
			@typeCodeExtensionTypeJpgId,--EXTENSION_FILE_TYPE_ID
			@typeCodeStorageTypeCloudDropboxId,--STORAGE_TYPE_ID
			NULL,--PET_ID
			NULL,--VACCINE_ID 
			@productId,--PRODUCT_ID 
			'-3')--CREATED_BY

	END

	COMMIT TRANSACTION

END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SELECT ERROR_NUMBER() AS ErrorNumber, ERROR_SEVERITY() AS ErrorSeverity, ERROR_STATE() AS ErrorState, ERROR_LINE() AS ErrorLine, ERROR_MESSAGE() AS ErrorMessage
	--THROW
END CATCH
